version: '3.9'
services:
  api_tinggal_nikah_auth : 
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    ports :
      - 3000:3000
    volumes : 
      - ./:/app
    env_file :
      - ./apps/auth/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres
  
  api_tinggal_nikah_user : 
    build:
      context: ./apps/user
      dockerfile: Dockerfile
    ports :
      - 3001:3001
    volumes : 
      - ./:/app
    env_file :
      - ./apps/user/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres
      - api_tinggal_nikah_auth

  
  api_tinggal_nikah_payment : 
    build:
      context: ./apps/payment
      dockerfile: Dockerfile
    ports :
      - 3002:3002
    volumes : 
      - ./:/app
    env_file :
      - ./apps/payment/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres

  api_tinggal_nikah_socket : 
    build:
      context: ./apps/socket
      dockerfile: Dockerfile
    ports :
      - 3003:3003
    volumes : 
      - ./:/app
    env_file :
      - ./apps/socket/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tinggal_nikah
      POSTGRES_USER: adriansyah
      POSTGRES_PASSWORD: adriansyahganteng
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./redis:/data
      
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"