version: '3.9'
services:
  api_tinggal_nikah_auth : 
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    ports :
      - 3000:3000
    volumes : 
      - ./:/app
    env_file :
      - ./apps/auth/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres
  
  api_tinggal_nikah_user : 
    build:
      context: ./apps/user
      dockerfile: Dockerfile
    ports :
      - 3001:3001
    volumes : 
      - ./:/app
    env_file :
      - ./apps/user/.env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres
      - api_tinggal_nikah_auth
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tinggal_nikah
      POSTGRES_USER: adriansyah
      POSTGRES_PASSWORD: adriansyahganteng
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data