version: '3.9'
services:
  api_tinggal_nikah : 
    build : .
    ports :
      - 3000:3000
    volumes : 
      - ./:/app
    env_file :
      - .env.local
    command: bash -c "go mod tidy && air -c .air.toml"
    depends_on :
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tinggal_nikah
      POSTGRES_USER: adriansyah
      POSTGRES_PASSWORD: adriansyahganteng
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data